### ISSUE TITLE
Ws-anywhere down due to possible server error

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/ws-anywhere#19]
![ws-anywhere2](https://user-images.githubusercontent.com/3299948/58704704-339cb680-83ad-11e9-829e-539ed5d0447f.gif)

Let's fix this and also a few things to improve:
- feedback on start/stop - i know this was considered but looking at this error i think it's better with feedback
- if `submit` (or anything else) errors on the server side let's display `Server error` (similar to `Invalid JSON format`).

**Comment by gomorizsolt** [comment]
> feedback on start/stop - i know this was considered but looking at this error i think it's better with feedback

The feedbacks are the usual icons, right?

**Comment by thisismydesign** [comment]
> The feedbacks are the usual icons, right?

Yes

**Comment by gomorizsolt** [comment]
So, if I'm right, you'd like to display either the success or error icon whenever the user clicks on the start/stop button? Sounds reasonable, however, this'd be misleading in the case below:

![2019-06-02 11 41 34](https://user-images.githubusercontent.com/30864202/58759506-78e6f280-852b-11e9-8871-6916daf62308.gif)

Hopefully you can spot my concern there. :)

---

One solution might be to display the icons next to the clicked button(s):

![2019-06-02 11 57 27](https://user-images.githubusercontent.com/30864202/58759648-b0569e80-852d-11e9-85b6-f5c50cd2ecaf.gif)

How do you like the one above?

**Comment by thisismydesign** [comment]
Yes, the second version is what I meant.

**Comment by gomorizsolt** [comment]
Based on our previous discussion with @thisismydesign, there's one more crucial task that needs to be done as part of the issue - besides the current ones in #20 and #21:
- `fetch` errors should also display `Server error` next to the relevant button(s) - this also applies to the disconnection functionality.

Bonus:
- how to distinguish errors in the `catch` blocks?

**Comment by gomorizsolt** [comment]
Resolved by #20, #21 and #22.
